name: Urbanizer Consumer Android

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Decode Service Account
      run: |
        echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" | base64 --decode > service-account.json

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build Debug APK
      run: ./gradlew :app:assembleDebug
      working-directory: AndroidConsumer

    - name: Upload APK to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        serviceCredentialsFile: service-account.json
        groups: testers
        file: AndroidConsumer/app/build/outputs/apk/debug/app-debug.apk
        releaseNotes: "Debug build from GitHub Actions"

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: AndroidConsumer/app/build/outputs/apk/debug/app-debug.apk