default_platform(:ios)

platform :ios do
  desc "Build and distribute to Firebase App Distribution"
  lane :beta do
    build_app(scheme: "Urbanizer")

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_IOS"],
      groups: "testers",
      release_notes: "CI build from GitHub Actions",
      firebase_cli_token: ENV["FIREBASE_TOKEN"]
    )
  end
end